interface Language {
	name: string
	code: string
}

const languages = [
	{ name: 'Afrikaans', code: 'af' },
	{ name: 'Amharic', code: 'am' },
	{ name: 'Arabic', code: 'ar' },
	{ name: 'Asturian', code: 'ast' },
	{ name: 'Azerbaijani', code: 'az' },
	{ name: 'Bashkir', code: 'ba' },
	{ name: 'Belarusian', code: 'be' },
	{ name: 'Bulgarian', code: 'bg' },
	{ name: 'Bengali', code: 'bn' },
	{ name: 'Breton', code: 'br' },
	{ name: 'Bosnian', code: 'bs' },
	{ name: 'Catalan; Valencian', code: 'ca' },
	{ name: 'Cebuano', code: 'ceb' },
	{ name: 'Czech', code: 'cs' },
	{ name: 'Welsh', code: 'cy' },
	{ name: 'Danish', code: 'da' },
	{ name: 'German', code: 'de' },
	{ name: 'Greek', code: 'el' },
	{ name: 'English', code: 'en' },
	{ name: 'Spanish', code: 'es' },
	{ name: 'Estonian', code: 'et' },
	{ name: 'Persian', code: 'fa' },
	{ name: 'Fulah', code: 'ff' },
	{ name: 'Finnish', code: 'fi' },
	{ name: 'French', code: 'fr' },
	{ name: 'Western Frisian', code: 'fy' },
	{ name: 'Irish', code: 'ga' },
	{ name: 'Gaelic; Scottish Gaelic', code: 'gd' },
	{ name: 'Galician', code: 'gl' },
	{ name: 'Gujarati', code: 'gu' },
	{ name: 'Hausa', code: 'ha' },
	{ name: 'Hebrew', code: 'he' },
	{ name: 'Hindi', code: 'hi' },
	{ name: 'Croatian', code: 'hr' },
	{ name: 'Haitian; Haitian Creole', code: 'ht' },
	{ name: 'Hungarian', code: 'hu' },
	{ name: 'Armenian', code: 'hy' },
	{ name: 'Indonesian', code: 'id' },
	{ name: 'Igbo', code: 'ig' },
	{ name: 'Iloko', code: 'ilo' },
	{ name: 'Icelandic', code: 'is' },
	{ name: 'Italian', code: 'it' },
	{ name: 'Japanese', code: 'ja' },
	{ name: 'Javanese', code: 'jv' },
	{ name: 'Georgian', code: 'ka' },
	{ name: 'Kazakh', code: 'kk' },
	{ name: 'Central Khmer', code: 'km' },
	{ name: 'Kannada', code: 'kn' },
	{ name: 'Korean', code: 'ko' },
	{ name: 'Luxembourgish; Letzeburgesch', code: 'lb' },
	{ name: 'Ganda', code: 'lg' },
	{ name: 'Lingala', code: 'ln' },
	{ name: 'Lao', code: 'lo' },
	{ name: 'Lithuanian', code: 'lt' },
	{ name: 'Latvian', code: 'lv' },
	{ name: 'Malagasy', code: 'mg' },
	{ name: 'Macedonian', code: 'mk' },
	{ name: 'Malayalam', code: 'ml' },
	{ name: 'Mongolian', code: 'mn' },
	{ name: 'Marathi', code: 'mr' },
	{ name: 'Malay', code: 'ms' },
	{ name: 'Burmese', code: 'my' },
	{ name: 'Nepali', code: 'ne' },
	{ name: 'Dutch; Flemish', code: 'nl' },
	{ name: 'Norwegian', code: 'no' },
	{ name: 'Northern Sotho', code: 'ns' },
	{ name: 'Occitan (post 1500)', code: 'oc' },
	{ name: 'Oriya', code: 'or' },
	{ name: 'Panjabi; Punjabi', code: 'pa' },
	{ name: 'Polish', code: 'pl' },
	{ name: 'Pushto; Pashto', code: 'ps' },
	{ name: 'Portuguese', code: 'pt' },
	{ name: 'Romanian; Moldavian; Moldovan', code: 'ro' },
	{ name: 'Russian', code: 'ru' },
	{ name: 'Sindhi', code: 'sd' },
	{ name: 'Sinhala; Sinhalese', code: 'si' },
	{ name: 'Slovak', code: 'sk' },
	{ name: 'Slovenian', code: 'sl' },
	{ name: 'Somali', code: 'so' },
	{ name: 'Albanian', code: 'sq' },
	{ name: 'Serbian', code: 'sr' },
	{ name: 'Swati', code: 'ss' },
	{ name: 'Sundanese', code: 'su' },
	{ name: 'Swedish', code: 'sv' },
	{ name: 'Swahili', code: 'sw' },
	{ name: 'Tamil', code: 'ta' },
	{ name: 'Thai', code: 'th' },
	{ name: 'Tagalog', code: 'tl' },
	{ name: 'Tswana', code: 'tn' },
	{ name: 'Turkish', code: 'tr' },
	{ name: 'Ukrainian', code: 'uk' },
	{ name: 'Urdu', code: 'ur' },
	{ name: 'Uzbek', code: 'uz' },
	{ name: 'Vietnamese', code: 'vi' },
	{ name: 'Wolof', code: 'wo' },
	{ name: 'Xhosa', code: 'xh' },
	{ name: 'Yiddish', code: 'yi' },
	{ name: 'Yoruba', code: 'yo' },
	{ name: 'Chinese', code: 'zh' },
	{ name: 'Zulu', code: 'zu' },
] as const satisfies Language[]

export default languages
